using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PSC.Blazor.Components.Icons
{
    public static class FlagData
    {
        public static List<FlagModel> FlagModels = new List<FlagModel>()
        {
            new FlagModel() { Code = "lg", FlagSquare = SVGFlags.lgbt_1, FlagWide = SVGFlags.lgbt_2, Iso = false, Name = "LGBT" },
            new FlagModel() { Code = "ac", FlagSquare = SVGFlags.ac_1, FlagWide = SVGFlags.ac_2, Iso = false, Name = "Ascension Island" },
            new FlagModel() { Code = "ad", FlagSquare = SVGFlags.ad_1, FlagWide = SVGFlags.ad_2, Iso = true, Name = "Andorra" },
            new FlagModel() { Code = "ae", FlagSquare = SVGFlags.ae_1, FlagWide = SVGFlags.ae_2, Iso = true, Name = "United Arab Emirates" },
            new FlagModel() { Code = "af", FlagSquare = SVGFlags.af_1, FlagWide = SVGFlags.af_2, Iso = true, Name = "Afghanistan" },
            new FlagModel() { Code = "ag", FlagSquare = SVGFlags.ag_1, FlagWide = SVGFlags.ag_2, Iso = true, Name = "Antigua and Barbuda" },
            new FlagModel() { Code = "ai", FlagSquare = SVGFlags.ai_1, FlagWide = SVGFlags.ai_2, Iso = true, Name = "Anguilla" },
            new FlagModel() { Code = "al", FlagSquare = SVGFlags.al_1, FlagWide = SVGFlags.al_2, Iso = true, Name = "Albania" },
            new FlagModel() { Code = "am", FlagSquare = SVGFlags.am_1, FlagWide = SVGFlags.am_2, Iso = true, Name = "Armenia" },
            new FlagModel() { Code = "ao", FlagSquare = SVGFlags.ao_1, FlagWide = SVGFlags.ao_2, Iso = true, Name = "Angola" },
            new FlagModel() { Code = "aq", FlagSquare = SVGFlags.aq_1, FlagWide = SVGFlags.aq_2, Iso = true, Name = "Antarctica" },
            new FlagModel() { Code = "ar", FlagSquare = SVGFlags.ar_1, FlagWide = SVGFlags.ar_2, Iso = true, Name = "Argentina" },
            new FlagModel() { Code = "as", FlagSquare = SVGFlags.as_1, FlagWide = SVGFlags.as_2, Iso = true, Name = "American Samoa" },
            new FlagModel() { Code = "at", FlagSquare = SVGFlags.at_1, FlagWide = SVGFlags.at_2, Iso = true, Name = "Austria" },
            new FlagModel() { Code = "au", FlagSquare = SVGFlags.au_1, FlagWide = SVGFlags.au_2, Iso = true, Name = "Australia" },
            new FlagModel() { Code = "aw", FlagSquare = SVGFlags.aw_1, FlagWide = SVGFlags.aw_2, Iso = true, Name = "Aruba" },
            new FlagModel() { Code = "ax", FlagSquare = SVGFlags.ax_1, FlagWide = SVGFlags.ax_2, Iso = true, Name = "Aland Islands" },
            new FlagModel() { Code = "az", FlagSquare = SVGFlags.az_1, FlagWide = SVGFlags.az_2, Iso = true, Name = "Azerbaijan" },
            new FlagModel() { Code = "ba", FlagSquare = SVGFlags.ba_1, FlagWide = SVGFlags.ba_2, Iso = true, Name = "Bosnia and Herzegovina" },
            new FlagModel() { Code = "bb", FlagSquare = SVGFlags.bb_1, FlagWide = SVGFlags.bb_2, Iso = true, Name = "Barbados" },
            new FlagModel() { Code = "bd", FlagSquare = SVGFlags.bd_1, FlagWide = SVGFlags.bd_2, Iso = true, Name = "Bangladesh" },
            new FlagModel() { Code = "be", FlagSquare = SVGFlags.be_1, FlagWide = SVGFlags.be_2, Iso = true, Name = "Belgium" },
            new FlagModel() { Code = "bf", FlagSquare = SVGFlags.bf_1, FlagWide = SVGFlags.bf_2, Iso = true, Name = "Burkina Faso" },
            new FlagModel() { Code = "bg", FlagSquare = SVGFlags.bg_1, FlagWide = SVGFlags.bg_2, Iso = true, Name = "Bulgaria" },
            new FlagModel() { Code = "bh", FlagSquare = SVGFlags.bh_1, FlagWide = SVGFlags.bh_2, Iso = true, Name = "Bahrain" },
            new FlagModel() { Code = "bi", FlagSquare = SVGFlags.bi_1, FlagWide = SVGFlags.bi_2, Iso = true, Name = "Burundi" },
            new FlagModel() { Code = "bj", FlagSquare = SVGFlags.bj_1, FlagWide = SVGFlags.bj_2, Iso = true, Name = "Benin" },
            new FlagModel() { Code = "bl", FlagSquare = SVGFlags.bl_1, FlagWide = SVGFlags.bl_2, Iso = true, Name = "Saint Barthélemy" },
            new FlagModel() { Code = "bm", FlagSquare = SVGFlags.bm_1, FlagWide = SVGFlags.bm_2, Iso = true, Name = "Bermuda" },
            new FlagModel() { Code = "bn", FlagSquare = SVGFlags.bn_1, FlagWide = SVGFlags.bn_2, Iso = true, Name = "Brunei Darussalam" },
            new FlagModel() { Code = "bo", FlagSquare = SVGFlags.bo_1, FlagWide = SVGFlags.bo_2, Iso = true, Name = "Bolivia (Plurinational State of)" },
            new FlagModel() { Code = "bq", FlagSquare = SVGFlags.bq_1, FlagWide = SVGFlags.bq_2, Iso = true, Name = "Bonaire, Sint Eustatius and Saba" },
            new FlagModel() { Code = "br", FlagSquare = SVGFlags.br_1, FlagWide = SVGFlags.br_2, Iso = true, Name = "Brazil" },
            new FlagModel() { Code = "bs", FlagSquare = SVGFlags.bs_1, FlagWide = SVGFlags.bs_2, Iso = true, Name = "Bahamas" },
            new FlagModel() { Code = "bt", FlagSquare = SVGFlags.bt_1, FlagWide = SVGFlags.bt_2, Iso = true, Name = "Bhutan" },
            new FlagModel() { Code = "bv", FlagSquare = SVGFlags.bv_1, FlagWide = SVGFlags.bv_2, Iso = true, Name = "Bouvet Island" },
            new FlagModel() { Code = "bw", FlagSquare = SVGFlags.bw_1, FlagWide = SVGFlags.bw_2, Iso = true, Name = "Botswana" },
            new FlagModel() { Code = "by", FlagSquare = SVGFlags.by_1, FlagWide = SVGFlags.by_2, Iso = true, Name = "Belarus" },
            new FlagModel() { Code = "bz", FlagSquare = SVGFlags.bz_1, FlagWide = SVGFlags.bz_2, Iso = true, Name = "Belize" },
            new FlagModel() { Code = "ca", FlagSquare = SVGFlags.ca_1, FlagWide = SVGFlags.ca_2, Iso = true, Name = "Canada" },
            new FlagModel() { Code = "cc", FlagSquare = SVGFlags.cc_1, FlagWide = SVGFlags.cc_2, Iso = true, Name = "Cocos (Keeling) Islands" },
            new FlagModel() { Code = "cd", FlagSquare = SVGFlags.cd_1, FlagWide = SVGFlags.cd_2, Iso = true, Name = "Democratic Republic of the Congo" },
            new FlagModel() { Code = "cf", FlagSquare = SVGFlags.cf_1, FlagWide = SVGFlags.cf_2, Iso = true, Name = "Central African Republic" },
            new FlagModel() { Code = "cg", FlagSquare = SVGFlags.cg_1, FlagWide = SVGFlags.cg_2, Iso = true, Name = "Republic of the Congo" },
            new FlagModel() { Code = "ch", FlagSquare = SVGFlags.ch_1, FlagWide = SVGFlags.ch_2, Iso = true, Name = "Switzerland" },
            new FlagModel() { Code = "ci", FlagSquare = SVGFlags.ci_1, FlagWide = SVGFlags.ci_2, Iso = true, Name = "Côte d'Ivoire" },
            new FlagModel() { Code = "ck", FlagSquare = SVGFlags.ck_1, FlagWide = SVGFlags.ck_2, Iso = true, Name = "Cook Islands" },
            new FlagModel() { Code = "cl", FlagSquare = SVGFlags.cl_1, FlagWide = SVGFlags.cl_2, Iso = true, Name = "Chile" },
            new FlagModel() { Code = "cm", FlagSquare = SVGFlags.cm_1, FlagWide = SVGFlags.cm_2, Iso = true, Name = "Cameroon" },
            new FlagModel() { Code = "cn", FlagSquare = SVGFlags.cn_1, FlagWide = SVGFlags.cn_2, Iso = true, Name = "China" },
            new FlagModel() { Code = "co", FlagSquare = SVGFlags.co_1, FlagWide = SVGFlags.co_2, Iso = true, Name = "Colombia" },
            new FlagModel() { Code = "cp", FlagSquare = SVGFlags.cp_1, FlagWide = SVGFlags.cp_2, Iso = false, Name = "Clipperton Island" },
            new FlagModel() { Code = "cr", FlagSquare = SVGFlags.cr_1, FlagWide = SVGFlags.cr_2, Iso = true, Name = "Costa Rica" },
            new FlagModel() { Code = "cu", FlagSquare = SVGFlags.cu_1, FlagWide = SVGFlags.cu_2, Iso = true, Name = "Cuba" },
            new FlagModel() { Code = "cv", FlagSquare = SVGFlags.cv_1, FlagWide = SVGFlags.cv_2, Iso = true, Name = "Cabo Verde" },
            new FlagModel() { Code = "cw", FlagSquare = SVGFlags.cw_1, FlagWide = SVGFlags.cw_2, Iso = true, Name = "Curaçao" },
            new FlagModel() { Code = "cx", FlagSquare = SVGFlags.cx_1, FlagWide = SVGFlags.cx_2, Iso = true, Name = "Christmas Island" },
            new FlagModel() { Code = "cy", FlagSquare = SVGFlags.cy_1, FlagWide = SVGFlags.cy_2, Iso = true, Name = "Cyprus" },
            new FlagModel() { Code = "cz", FlagSquare = SVGFlags.cz_1, FlagWide = SVGFlags.cz_2, Iso = true, Name = "Czech Republic" },
            new FlagModel() { Code = "de", FlagSquare = SVGFlags.de_1, FlagWide = SVGFlags.de_2, Iso = true, Name = "Germany" },
            new FlagModel() { Code = "dg", FlagSquare = SVGFlags.dg_1, FlagWide = SVGFlags.dg_2, Iso = false, Name = "Diego Garcia" },
            new FlagModel() { Code = "dj", FlagSquare = SVGFlags.dj_1, FlagWide = SVGFlags.dj_2, Iso = true, Name = "Djibouti" },
            new FlagModel() { Code = "dk", FlagSquare = SVGFlags.dk_1, FlagWide = SVGFlags.dk_2, Iso = true, Name = "Denmark" },
            new FlagModel() { Code = "dm", FlagSquare = SVGFlags.dm_1, FlagWide = SVGFlags.dm_2, Iso = true, Name = "Dominica" },
            new FlagModel() { Code = "do", FlagSquare = SVGFlags.do_1, FlagWide = SVGFlags.do_2, Iso = true, Name = "Dominican Republic" },
            new FlagModel() { Code = "dz", FlagSquare = SVGFlags.dz_1, FlagWide = SVGFlags.dz_2, Iso = true, Name = "Algeria" },
            new FlagModel() { Code = "ea", FlagSquare = SVGFlags.ea_1, FlagWide = SVGFlags.ea_2, Iso = false, Name = "Ceuta & Melilla" },
            new FlagModel() { Code = "ec", FlagSquare = SVGFlags.ec_1, FlagWide = SVGFlags.ec_2, Iso = true, Name = "Ecuador" },
            new FlagModel() { Code = "ee", FlagSquare = SVGFlags.ee_1, FlagWide = SVGFlags.ee_2, Iso = true, Name = "Estonia" },
            new FlagModel() { Code = "eg", FlagSquare = SVGFlags.eg_1, FlagWide = SVGFlags.eg_2, Iso = true, Name = "Egypt" },
            new FlagModel() { Code = "eh", FlagSquare = SVGFlags.eh_1, FlagWide = SVGFlags.eh_2, Iso = true, Name = "Western Sahara" },
            new FlagModel() { Code = "er", FlagSquare = SVGFlags.er_1, FlagWide = SVGFlags.er_2, Iso = true, Name = "Eritrea" },
            new FlagModel() { Code = "es", FlagSquare = SVGFlags.es_1, FlagWide = SVGFlags.es_2, Iso = true, Name = "Spain" },
            new FlagModel() { Code = "es-ct", FlagSquare = SVGFlags.es_ct_1, FlagWide = SVGFlags.es_ct_2, Iso = false, Name = "Catalonia" },
            new FlagModel() { Code = "es-ga", FlagSquare = SVGFlags.es_ga_1, FlagWide = SVGFlags.es_ga_2, Iso = false, Name = "Galicia" },
            new FlagModel() { Code = "et", FlagSquare = SVGFlags.et_1, FlagWide = SVGFlags.et_2, Iso = true, Name = "Ethiopia" },
            new FlagModel() { Code = "eu", FlagSquare = SVGFlags.eu_1, FlagWide = SVGFlags.eu_2, Iso = false, Name = "Europe" },
            new FlagModel() { Code = "fi", FlagSquare = SVGFlags.fi_1, FlagWide = SVGFlags.fi_2, Iso = true, Name = "Finland" },
            new FlagModel() { Code = "fj", FlagSquare = SVGFlags.fj_1, FlagWide = SVGFlags.fj_2, Iso = true, Name = "Fiji" },
            new FlagModel() { Code = "fk", FlagSquare = SVGFlags.fk_1, FlagWide = SVGFlags.fk_2, Iso = true, Name = "Falkland Islands" },
            new FlagModel() { Code = "fm", FlagSquare = SVGFlags.fm_1, FlagWide = SVGFlags.fm_2, Iso = true, Name = "Federated States of Micronesia" },
            new FlagModel() { Code = "fo", FlagSquare = SVGFlags.fo_1, FlagWide = SVGFlags.fo_2, Iso = true, Name = "Faroe Islands" },
            new FlagModel() { Code = "fr", FlagSquare = SVGFlags.fr_1, FlagWide = SVGFlags.fr_2, Iso = true, Name = "France" },
            new FlagModel() { Code = "ga", FlagSquare = SVGFlags.ga_1, FlagWide = SVGFlags.ga_2, Iso = true, Name = "Gabon" },
            new FlagModel() { Code = "gb", FlagSquare = SVGFlags.gb_1, FlagWide = SVGFlags.gb_2, Iso = true, Name = "United Kingdom" },
            new FlagModel() { Code = "gb-eng", FlagSquare = SVGFlags.gb_eng_1, FlagWide = SVGFlags.gb_eng_2, Iso = false, Name = "England" },
            new FlagModel() { Code = "gb-nir", FlagSquare = SVGFlags.gb_nir_1, FlagWide = SVGFlags.gb_nir_2, Iso = false, Name = "Northern Ireland" },
            new FlagModel() { Code = "gb-sct", FlagSquare = SVGFlags.gb_sct_1, FlagWide = SVGFlags.gb_sct_2, Iso = false, Name = "Scotland" },
            new FlagModel() { Code = "gb-wls", FlagSquare = SVGFlags.gb_wls_1, FlagWide = SVGFlags.gb_wls_2, Iso = false, Name = "Wales" },
            new FlagModel() { Code = "gd", FlagSquare = SVGFlags.gd_1, FlagWide = SVGFlags.gd_2, Iso = true, Name = "Grenada" },
            new FlagModel() { Code = "ge", FlagSquare = SVGFlags.ge_1, FlagWide = SVGFlags.ge_2, Iso = true, Name = "Georgia" },
            new FlagModel() { Code = "gf", FlagSquare = SVGFlags.gf_1, FlagWide = SVGFlags.gf_2, Iso = true, Name = "French Guiana" },
            new FlagModel() { Code = "gg", FlagSquare = SVGFlags.gg_1, FlagWide = SVGFlags.gg_2, Iso = true, Name = "Guernsey" },
            new FlagModel() { Code = "gh", FlagSquare = SVGFlags.gh_1, FlagWide = SVGFlags.gh_2, Iso = true, Name = "Ghana" },
            new FlagModel() { Code = "gi", FlagSquare = SVGFlags.gi_1, FlagWide = SVGFlags.gi_2, Iso = true, Name = "Gibraltar" },
            new FlagModel() { Code = "gl", FlagSquare = SVGFlags.gl_1, FlagWide = SVGFlags.gl_2, Iso = true, Name = "Greenland" },
            new FlagModel() { Code = "gm", FlagSquare = SVGFlags.gm_1, FlagWide = SVGFlags.gm_2, Iso = true, Name = "Gambia" },
            new FlagModel() { Code = "gn", FlagSquare = SVGFlags.gn_1, FlagWide = SVGFlags.gn_2, Iso = true, Name = "Guinea" },
            new FlagModel() { Code = "gp", FlagSquare = SVGFlags.gp_1, FlagWide = SVGFlags.gp_2, Iso = true, Name = "Guadeloupe" },
            new FlagModel() { Code = "gq", FlagSquare = SVGFlags.gq_1, FlagWide = SVGFlags.gq_2, Iso = true, Name = "Equatorial Guinea" },
            new FlagModel() { Code = "gr", FlagSquare = SVGFlags.gr_1, FlagWide = SVGFlags.gr_2, Iso = true, Name = "Greece" },
            new FlagModel() { Code = "gs", FlagSquare = SVGFlags.gs_1, FlagWide = SVGFlags.gs_2, Iso = true, Name = "South Georgia and the South Sandwich Islands" },
            new FlagModel() { Code = "gt", FlagSquare = SVGFlags.gt_1, FlagWide = SVGFlags.gt_2, Iso = true, Name = "Guatemala" },
            new FlagModel() { Code = "gu", FlagSquare = SVGFlags.gu_1, FlagWide = SVGFlags.gu_2, Iso = true, Name = "Guam" },
            new FlagModel() { Code = "gw", FlagSquare = SVGFlags.gw_1, FlagWide = SVGFlags.gw_2, Iso = true, Name = "Guinea-Bissau" },
            new FlagModel() { Code = "gy", FlagSquare = SVGFlags.gy_1, FlagWide = SVGFlags.gy_2, Iso = true, Name = "Guyana" },
            new FlagModel() { Code = "hk", FlagSquare = SVGFlags.hk_1, FlagWide = SVGFlags.hk_2, Iso = true, Name = "Hong Kong" },
            new FlagModel() { Code = "hm", FlagSquare = SVGFlags.hm_1, FlagWide = SVGFlags.hm_2, Iso = true, Name = "Heard Island and McDonald Islands" },
            new FlagModel() { Code = "hn", FlagSquare = SVGFlags.hn_1, FlagWide = SVGFlags.hn_2, Iso = true, Name = "Honduras" },
            new FlagModel() { Code = "hr", FlagSquare = SVGFlags.hr_1, FlagWide = SVGFlags.hr_2, Iso = true, Name = "Croatia" },
            new FlagModel() { Code = "ht", FlagSquare = SVGFlags.ht_1, FlagWide = SVGFlags.ht_2, Iso = true, Name = "Haiti" },
            new FlagModel() { Code = "hu", FlagSquare = SVGFlags.hu_1, FlagWide = SVGFlags.hu_2, Iso = true, Name = "Hungary" },
            new FlagModel() { Code = "ic", FlagSquare = SVGFlags.ic_1, FlagWide = SVGFlags.ic_2, Iso = false, Name = "Canary Islands" },
            new FlagModel() { Code = "id", FlagSquare = SVGFlags.id_1, FlagWide = SVGFlags.id_2, Iso = true, Name = "Indonesia" },
            new FlagModel() { Code = "ie", FlagSquare = SVGFlags.ie_1, FlagWide = SVGFlags.ie_2, Iso = true, Name = "Ireland" },
            new FlagModel() { Code = "il", FlagSquare = SVGFlags.il_1, FlagWide = SVGFlags.il_2, Iso = true, Name = "Israel" },
            new FlagModel() { Code = "im", FlagSquare = SVGFlags.im_1, FlagWide = SVGFlags.im_2, Iso = true, Name = "Isle of Man" },
            new FlagModel() { Code = "in", FlagSquare = SVGFlags.in_1, FlagWide = SVGFlags.in_2, Iso = true, Name = "India" },
            new FlagModel() { Code = "io", FlagSquare = SVGFlags.io_1, FlagWide = SVGFlags.io_2, Iso = true, Name = "British Indian Ocean Territory" },
            new FlagModel() { Code = "iq", FlagSquare = SVGFlags.iq_1, FlagWide = SVGFlags.iq_2, Iso = true, Name = "Iraq" },
            new FlagModel() { Code = "ir", FlagSquare = SVGFlags.ir_1, FlagWide = SVGFlags.ir_2, Iso = true, Name = "Iran (Islamic Republic of)" },
            new FlagModel() { Code = "is", FlagSquare = SVGFlags.is_1, FlagWide = SVGFlags.is_2, Iso = true, Name = "Iceland" },
            new FlagModel() { Code = "it", FlagSquare = SVGFlags.it_1, FlagWide = SVGFlags.it_2, Iso = true, Name = "Italy" },
            new FlagModel() { Code = "je", FlagSquare = SVGFlags.je_1, FlagWide = SVGFlags.je_2, Iso = true, Name = "Jersey" },
            new FlagModel() { Code = "jm", FlagSquare = SVGFlags.jm_1, FlagWide = SVGFlags.jm_2, Iso = true, Name = "Jamaica" },
            new FlagModel() { Code = "jo", FlagSquare = SVGFlags.jo_1, FlagWide = SVGFlags.jo_2, Iso = true, Name = "Jordan" },
            new FlagModel() { Code = "jp", FlagSquare = SVGFlags.jp_1, FlagWide = SVGFlags.jp_2, Iso = true, Name = "Japan" },
            new FlagModel() { Code = "ke", FlagSquare = SVGFlags.ke_1, FlagWide = SVGFlags.ke_2, Iso = true, Name = "Kenya" },
            new FlagModel() { Code = "kg", FlagSquare = SVGFlags.kg_1, FlagWide = SVGFlags.kg_2, Iso = true, Name = "Kyrgyzstan" },
            new FlagModel() { Code = "kh", FlagSquare = SVGFlags.kh_1, FlagWide = SVGFlags.kh_2, Iso = true, Name = "Cambodia" },
            new FlagModel() { Code = "ki", FlagSquare = SVGFlags.ki_1, FlagWide = SVGFlags.ki_2, Iso = true, Name = "Kiribati" },
            new FlagModel() { Code = "km", FlagSquare = SVGFlags.km_1, FlagWide = SVGFlags.km_2, Iso = true, Name = "Comoros" },
            new FlagModel() { Code = "kn", FlagSquare = SVGFlags.kn_1, FlagWide = SVGFlags.kn_2, Iso = true, Name = "Saint Kitts and Nevis" },
            new FlagModel() { Code = "kp", FlagSquare = SVGFlags.kp_1, FlagWide = SVGFlags.kp_2, Iso = true, Name = "North Korea" },
            new FlagModel() { Code = "kr", FlagSquare = SVGFlags.kr_1, FlagWide = SVGFlags.kr_2, Iso = true, Name = "South Korea" },
            new FlagModel() { Code = "kw", FlagSquare = SVGFlags.kw_1, FlagWide = SVGFlags.kw_2, Iso = true, Name = "Kuwait" },
            new FlagModel() { Code = "ky", FlagSquare = SVGFlags.ky_1, FlagWide = SVGFlags.ky_2, Iso = true, Name = "Cayman Islands" },
            new FlagModel() { Code = "kz", FlagSquare = SVGFlags.kz_1, FlagWide = SVGFlags.kz_2, Iso = true, Name = "Kazakhstan" },
            new FlagModel() { Code = "la", FlagSquare = SVGFlags.la_1, FlagWide = SVGFlags.la_2, Iso = true, Name = "Laos" },
            new FlagModel() { Code = "lb", FlagSquare = SVGFlags.lb_1, FlagWide = SVGFlags.lb_2, Iso = true, Name = "Lebanon" },
            new FlagModel() { Code = "lc", FlagSquare = SVGFlags.lc_1, FlagWide = SVGFlags.lc_2, Iso = true, Name = "Saint Lucia" },
            new FlagModel() { Code = "li", FlagSquare = SVGFlags.li_1, FlagWide = SVGFlags.li_2, Iso = true, Name = "Liechtenstein" },
            new FlagModel() { Code = "lk", FlagSquare = SVGFlags.lk_1, FlagWide = SVGFlags.lk_2, Iso = true, Name = "Sri Lanka" },
            new FlagModel() { Code = "lr", FlagSquare = SVGFlags.lr_1, FlagWide = SVGFlags.lr_2, Iso = true, Name = "Liberia" },
            new FlagModel() { Code = "ls", FlagSquare = SVGFlags.ls_1, FlagWide = SVGFlags.ls_2, Iso = true, Name = "Lesotho" },
            new FlagModel() { Code = "lt", FlagSquare = SVGFlags.lt_1, FlagWide = SVGFlags.lt_2, Iso = true, Name = "Lithuania" },
            new FlagModel() { Code = "lu", FlagSquare = SVGFlags.lu_1, FlagWide = SVGFlags.lu_2, Iso = true, Name = "Luxembourg" },
            new FlagModel() { Code = "lv", FlagSquare = SVGFlags.lv_1, FlagWide = SVGFlags.lv_2, Iso = true, Name = "Latvia" },
            new FlagModel() { Code = "ly", FlagSquare = SVGFlags.ly_1, FlagWide = SVGFlags.ly_2, Iso = true, Name = "Libya" },
            new FlagModel() { Code = "ma", FlagSquare = SVGFlags.ma_1, FlagWide = SVGFlags.ma_2, Iso = true, Name = "Morocco" },
            new FlagModel() { Code = "mc", FlagSquare = SVGFlags.mc_1, FlagWide = SVGFlags.mc_2, Iso = true, Name = "Monaco" },
            new FlagModel() { Code = "md", FlagSquare = SVGFlags.md_1, FlagWide = SVGFlags.md_2, Iso = true, Name = "Moldova" },
            new FlagModel() { Code = "me", FlagSquare = SVGFlags.me_1, FlagWide = SVGFlags.me_2, Iso = true, Name = "Montenegro" },
            new FlagModel() { Code = "mf", FlagSquare = SVGFlags.mf_1, FlagWide = SVGFlags.mf_2, Iso = true, Name = "Saint Martin" },
            new FlagModel() { Code = "mg", FlagSquare = SVGFlags.mg_1, FlagWide = SVGFlags.mg_2, Iso = true, Name = "Madagascar" },
            new FlagModel() { Code = "mh", FlagSquare = SVGFlags.mh_1, FlagWide = SVGFlags.mh_2, Iso = true, Name = "Marshall Islands" },
            new FlagModel() { Code = "mk", FlagSquare = SVGFlags.mk_1, FlagWide = SVGFlags.mk_2, Iso = true, Name = "North Macedonia" },
            new FlagModel() { Code = "ml", FlagSquare = SVGFlags.ml_1, FlagWide = SVGFlags.ml_2, Iso = true, Name = "Mali" },
            new FlagModel() { Code = "mm", FlagSquare = SVGFlags.mm_1, FlagWide = SVGFlags.mm_2, Iso = true, Name = "Myanmar" },
            new FlagModel() { Code = "mn", FlagSquare = SVGFlags.mn_1, FlagWide = SVGFlags.mn_2, Iso = true, Name = "Mongolia" },
            new FlagModel() { Code = "mo", FlagSquare = SVGFlags.mo_1, FlagWide = SVGFlags.mo_2, Iso = true, Name = "Macau" },
            new FlagModel() { Code = "mp", FlagSquare = SVGFlags.mp_1, FlagWide = SVGFlags.mp_2, Iso = true, Name = "Northern Mariana Islands" },
            new FlagModel() { Code = "mq", FlagSquare = SVGFlags.mq_1, FlagWide = SVGFlags.mq_2, Iso = true, Name = "Martinique" },
            new FlagModel() { Code = "mr", FlagSquare = SVGFlags.mr_1, FlagWide = SVGFlags.mr_2, Iso = true, Name = "Mauritania" },
            new FlagModel() { Code = "ms", FlagSquare = SVGFlags.ms_1, FlagWide = SVGFlags.ms_2, Iso = true, Name = "Montserrat" },
            new FlagModel() { Code = "mt", FlagSquare = SVGFlags.mt_1, FlagWide = SVGFlags.mt_2, Iso = true, Name = "Malta" },
            new FlagModel() { Code = "mu", FlagSquare = SVGFlags.mu_1, FlagWide = SVGFlags.mu_2, Iso = true, Name = "Mauritius" },
            new FlagModel() { Code = "mv", FlagSquare = SVGFlags.mv_1, FlagWide = SVGFlags.mv_2, Iso = true, Name = "Maldives" },
            new FlagModel() { Code = "mw", FlagSquare = SVGFlags.mw_1, FlagWide = SVGFlags.mw_2, Iso = true, Name = "Malawi" },
            new FlagModel() { Code = "mx", FlagSquare = SVGFlags.mx_1, FlagWide = SVGFlags.mx_2, Iso = true, Name = "Mexico" },
            new FlagModel() { Code = "my", FlagSquare = SVGFlags.my_1, FlagWide = SVGFlags.my_2, Iso = true, Name = "Malaysia" },
            new FlagModel() { Code = "mz", FlagSquare = SVGFlags.mz_1, FlagWide = SVGFlags.mz_2, Iso = true, Name = "Mozambique" },
            new FlagModel() { Code = "na", FlagSquare = SVGFlags.na_1, FlagWide = SVGFlags.na_2, Iso = true, Name = "Namibia" },
            new FlagModel() { Code = "nc", FlagSquare = SVGFlags.nc_1, FlagWide = SVGFlags.nc_2, Iso = true, Name = "New Caledonia" },
            new FlagModel() { Code = "ne", FlagSquare = SVGFlags.ne_1, FlagWide = SVGFlags.ne_2, Iso = true, Name = "Niger" },
            new FlagModel() { Code = "nf", FlagSquare = SVGFlags.nf_1, FlagWide = SVGFlags.nf_2, Iso = true, Name = "Norfolk Island" },
            new FlagModel() { Code = "ng", FlagSquare = SVGFlags.ng_1, FlagWide = SVGFlags.ng_2, Iso = true, Name = "Nigeria" },
            new FlagModel() { Code = "ni", FlagSquare = SVGFlags.ni_1, FlagWide = SVGFlags.ni_2, Iso = true, Name = "Nicaragua" },
            new FlagModel() { Code = "nl", FlagSquare = SVGFlags.nl_1, FlagWide = SVGFlags.nl_2, Iso = true, Name = "Netherlands" },
            new FlagModel() { Code = "no", FlagSquare = SVGFlags.no_1, FlagWide = SVGFlags.no_2, Iso = true, Name = "Norway" },
            new FlagModel() { Code = "np", FlagSquare = SVGFlags.np_1, FlagWide = SVGFlags.np_2, Iso = true, Name = "Nepal" },
            new FlagModel() { Code = "nr", FlagSquare = SVGFlags.nr_1, FlagWide = SVGFlags.nr_2, Iso = true, Name = "Nauru" },
            new FlagModel() { Code = "nu", FlagSquare = SVGFlags.nu_1, FlagWide = SVGFlags.nu_2, Iso = true, Name = "Niue" },
            new FlagModel() { Code = "nz", FlagSquare = SVGFlags.nz_1, FlagWide = SVGFlags.nz_2, Iso = true, Name = "New Zealand" },
            new FlagModel() { Code = "om", FlagSquare = SVGFlags.om_1, FlagWide = SVGFlags.om_2, Iso = true, Name = "Oman" },
            new FlagModel() { Code = "pa", FlagSquare = SVGFlags.pa_1, FlagWide = SVGFlags.pa_2, Iso = true, Name = "Panama" },
            new FlagModel() { Code = "pe", FlagSquare = SVGFlags.pe_1, FlagWide = SVGFlags.pe_2, Iso = true, Name = "Peru" },
            new FlagModel() { Code = "pf", FlagSquare = SVGFlags.pf_1, FlagWide = SVGFlags.pf_2, Iso = true, Name = "French Polynesia" },
            new FlagModel() { Code = "pg", FlagSquare = SVGFlags.pg_1, FlagWide = SVGFlags.pg_2, Iso = true, Name = "Papua New Guinea" },
            new FlagModel() { Code = "ph", FlagSquare = SVGFlags.ph_1, FlagWide = SVGFlags.ph_2, Iso = true, Name = "Philippines" },
            new FlagModel() { Code = "pk", FlagSquare = SVGFlags.pk_1, FlagWide = SVGFlags.pk_2, Iso = true, Name = "Pakistan" },
            new FlagModel() { Code = "pl", FlagSquare = SVGFlags.pl_1, FlagWide = SVGFlags.pl_2, Iso = true, Name = "Poland" },
            new FlagModel() { Code = "pm", FlagSquare = SVGFlags.pm_1, FlagWide = SVGFlags.pm_2, Iso = true, Name = "Saint Pierre and Miquelon" },
            new FlagModel() { Code = "pn", FlagSquare = SVGFlags.pn_1, FlagWide = SVGFlags.pn_2, Iso = true, Name = "Pitcairn" },
            new FlagModel() { Code = "pr", FlagSquare = SVGFlags.pr_1, FlagWide = SVGFlags.pr_2, Iso = true, Name = "Puerto Rico" },
            new FlagModel() { Code = "ps", FlagSquare = SVGFlags.ps_1, FlagWide = SVGFlags.ps_2, Iso = true, Name = "State of Palestine" },
            new FlagModel() { Code = "pt", FlagSquare = SVGFlags.pt_1, FlagWide = SVGFlags.pt_2, Iso = true, Name = "Portugal" },
            new FlagModel() { Code = "pw", FlagSquare = SVGFlags.pw_1, FlagWide = SVGFlags.pw_2, Iso = true, Name = "Palau" },
            new FlagModel() { Code = "py", FlagSquare = SVGFlags.py_1, FlagWide = SVGFlags.py_2, Iso = true, Name = "Paraguay" },
            new FlagModel() { Code = "qa", FlagSquare = SVGFlags.qa_1, FlagWide = SVGFlags.qa_2, Iso = true, Name = "Qatar" },
            new FlagModel() { Code = "re", FlagSquare = SVGFlags.re_1, FlagWide = SVGFlags.re_2, Iso = true, Name = "Réunion" },
            new FlagModel() { Code = "ro", FlagSquare = SVGFlags.ro_1, FlagWide = SVGFlags.ro_2, Iso = true, Name = "Romania" },
            new FlagModel() { Code = "rs", FlagSquare = SVGFlags.rs_1, FlagWide = SVGFlags.rs_2, Iso = true, Name = "Serbia" },
            new FlagModel() { Code = "ru", FlagSquare = SVGFlags.ru_1, FlagWide = SVGFlags.ru_2, Iso = true, Name = "Russia" },
            new FlagModel() { Code = "rw", FlagSquare = SVGFlags.rw_1, FlagWide = SVGFlags.rw_2, Iso = true, Name = "Rwanda" },
            new FlagModel() { Code = "sa", FlagSquare = SVGFlags.sa_1, FlagWide = SVGFlags.sa_2, Iso = true, Name = "Saudi Arabia" },
            new FlagModel() { Code = "sb", FlagSquare = SVGFlags.sb_1, FlagWide = SVGFlags.sb_2, Iso = true, Name = "Solomon Islands" },
            new FlagModel() { Code = "sc", FlagSquare = SVGFlags.sc_1, FlagWide = SVGFlags.sc_2, Iso = true, Name = "Seychelles" },
            new FlagModel() { Code = "sd", FlagSquare = SVGFlags.sd_1, FlagWide = SVGFlags.sd_2, Iso = true, Name = "Sudan" },
            new FlagModel() { Code = "se", FlagSquare = SVGFlags.se_1, FlagWide = SVGFlags.se_2, Iso = true, Name = "Sweden" },
            new FlagModel() { Code = "sg", FlagSquare = SVGFlags.sg_1, FlagWide = SVGFlags.sg_2, Iso = true, Name = "Singapore" },
            new FlagModel() { Code = "sh", FlagSquare = SVGFlags.sh_1, FlagWide = SVGFlags.sh_2, Iso = true, Name = "Saint Helena, Ascension and Tristan da Cunha" },
            new FlagModel() { Code = "si", FlagSquare = SVGFlags.si_1, FlagWide = SVGFlags.si_2, Iso = true, Name = "Slovenia" },
            new FlagModel() { Code = "sj", FlagSquare = SVGFlags.sj_1, FlagWide = SVGFlags.sj_2, Iso = true, Name = "Svalbard and Jan Mayen" },
            new FlagModel() { Code = "sk", FlagSquare = SVGFlags.sk_1, FlagWide = SVGFlags.sk_2, Iso = true, Name = "Slovakia" },
            new FlagModel() { Code = "sl", FlagSquare = SVGFlags.sl_1, FlagWide = SVGFlags.sl_2, Iso = true, Name = "Sierra Leone" },
            new FlagModel() { Code = "sm", FlagSquare = SVGFlags.sm_1, FlagWide = SVGFlags.sm_2, Iso = true, Name = "San Marino" },
            new FlagModel() { Code = "sn", FlagSquare = SVGFlags.sn_1, FlagWide = SVGFlags.sn_2, Iso = true, Name = "Senegal" },
            new FlagModel() { Code = "so", FlagSquare = SVGFlags.so_1, FlagWide = SVGFlags.so_2, Iso = true, Name = "Somalia" },
            new FlagModel() { Code = "sr", FlagSquare = SVGFlags.sr_1, FlagWide = SVGFlags.sr_2, Iso = true, Name = "Suriname" },
            new FlagModel() { Code = "ss", FlagSquare = SVGFlags.ss_1, FlagWide = SVGFlags.ss_2, Iso = true, Name = "South Sudan" },
            new FlagModel() { Code = "st", FlagSquare = SVGFlags.st_1, FlagWide = SVGFlags.st_2, Iso = true, Name = "Sao Tome and Principe" },
            new FlagModel() { Code = "sv", FlagSquare = SVGFlags.sv_1, FlagWide = SVGFlags.sv_2, Iso = true, Name = "El Salvador" },
            new FlagModel() { Code = "sx", FlagSquare = SVGFlags.sx_1, FlagWide = SVGFlags.sx_2, Iso = true, Name = "Sint Maarten" },
            new FlagModel() { Code = "sy", FlagSquare = SVGFlags.sy_1, FlagWide = SVGFlags.sy_2, Iso = true, Name = "Syrian Arab Republic" },
            new FlagModel() { Code = "sz", FlagSquare = SVGFlags.sz_1, FlagWide = SVGFlags.sz_2, Iso = true, Name = "Swaziland" },
            new FlagModel() { Code = "ta", FlagSquare = SVGFlags.ta_1, FlagWide = SVGFlags.ta_2, Iso = false, Name = "Tristan da Cunha" },
            new FlagModel() { Code = "tc", FlagSquare = SVGFlags.tc_1, FlagWide = SVGFlags.tc_2, Iso = true, Name = "Turks and Caicos Islands" },
            new FlagModel() { Code = "td", FlagSquare = SVGFlags.td_1, FlagWide = SVGFlags.td_2, Iso = true, Name = "Chad" },
            new FlagModel() { Code = "tf", FlagSquare = SVGFlags.tf_1, FlagWide = SVGFlags.tf_2, Iso = true, Name = "French Southern Territories" },
            new FlagModel() { Code = "tg", FlagSquare = SVGFlags.tg_1, FlagWide = SVGFlags.tg_2, Iso = true, Name = "Togo" },
            new FlagModel() { Code = "th", FlagSquare = SVGFlags.th_1, FlagWide = SVGFlags.th_2, Iso = true, Name = "Thailand" },
            new FlagModel() { Code = "tj", FlagSquare = SVGFlags.tj_1, FlagWide = SVGFlags.tj_2, Iso = true, Name = "Tajikistan" },
            new FlagModel() { Code = "tk", FlagSquare = SVGFlags.tk_1, FlagWide = SVGFlags.tk_2, Iso = true, Name = "Tokelau" },
            new FlagModel() { Code = "tl", FlagSquare = SVGFlags.tl_1, FlagWide = SVGFlags.tl_2, Iso = true, Name = "Timor-Leste" },
            new FlagModel() { Code = "tm", FlagSquare = SVGFlags.tm_1, FlagWide = SVGFlags.tm_2, Iso = true, Name = "Turkmenistan" },
            new FlagModel() { Code = "tn", FlagSquare = SVGFlags.tn_1, FlagWide = SVGFlags.tn_2, Iso = true, Name = "Tunisia" },
            new FlagModel() { Code = "to", FlagSquare = SVGFlags.to_1, FlagWide = SVGFlags.to_2, Iso = true, Name = "Tonga" },
            new FlagModel() { Code = "tr", FlagSquare = SVGFlags.tr_1, FlagWide = SVGFlags.tr_2, Iso = true, Name = "Turkey" },
            new FlagModel() { Code = "tt", FlagSquare = SVGFlags.tt_1, FlagWide = SVGFlags.tt_2, Iso = true, Name = "Trinidad and Tobago" },
            new FlagModel() { Code = "tv", FlagSquare = SVGFlags.tv_1, FlagWide = SVGFlags.tv_2, Iso = true, Name = "Tuvalu" },
            new FlagModel() { Code = "tw", FlagSquare = SVGFlags.tw_1, FlagWide = SVGFlags.tw_2, Iso = true, Name = "Taiwan" },
            new FlagModel() { Code = "tz", FlagSquare = SVGFlags.tz_1, FlagWide = SVGFlags.tz_2, Iso = true, Name = "Tanzania" },
            new FlagModel() { Code = "ua", FlagSquare = SVGFlags.ua_1, FlagWide = SVGFlags.ua_2, Iso = true, Name = "Ukraine" },
            new FlagModel() { Code = "ug", FlagSquare = SVGFlags.ug_1, FlagWide = SVGFlags.ug_2, Iso = true, Name = "Uganda" },
            new FlagModel() { Code = "um", FlagSquare = SVGFlags.um_1, FlagWide = SVGFlags.um_2, Iso = true, Name = "United States Minor Outlying Islands" },
            new FlagModel() { Code = "un", FlagSquare = SVGFlags.un_1, FlagWide = SVGFlags.un_2, Iso = false, Name = "United Nations" },
            new FlagModel() { Code = "us", FlagSquare = SVGFlags.us_1, FlagWide = SVGFlags.us_2, Iso = true, Name = "United States of America" },
            new FlagModel() { Code = "uy", FlagSquare = SVGFlags.uy_1, FlagWide = SVGFlags.uy_2, Iso = true, Name = "Uruguay" },
            new FlagModel() { Code = "uz", FlagSquare = SVGFlags.uz_1, FlagWide = SVGFlags.uz_2, Iso = true, Name = "Uzbekistan" },
            new FlagModel() { Code = "va", FlagSquare = SVGFlags.va_1, FlagWide = SVGFlags.va_2, Iso = true, Name = "Holy See" },
            new FlagModel() { Code = "vc", FlagSquare = SVGFlags.vc_1, FlagWide = SVGFlags.vc_2, Iso = true, Name = "Saint Vincent and the Grenadines" },
            new FlagModel() { Code = "ve", FlagSquare = SVGFlags.ve_1, FlagWide = SVGFlags.ve_2, Iso = true, Name = "Venezuela (Bolivarian Republic of)" },
            new FlagModel() { Code = "vg", FlagSquare = SVGFlags.vg_1, FlagWide = SVGFlags.vg_2, Iso = true, Name = "Virgin Islands (British)" },
            new FlagModel() { Code = "vi", FlagSquare = SVGFlags.vi_1, FlagWide = SVGFlags.vi_2, Iso = true, Name = "Virgin Islands (U.S.)" },
            new FlagModel() { Code = "vn", FlagSquare = SVGFlags.vn_1, FlagWide = SVGFlags.vn_2, Iso = true, Name = "Vietnam" },
            new FlagModel() { Code = "vu", FlagSquare = SVGFlags.vu_1, FlagWide = SVGFlags.vu_2, Iso = true, Name = "Vanuatu" },
            new FlagModel() { Code = "wf", FlagSquare = SVGFlags.wf_1, FlagWide = SVGFlags.wf_2, Iso = true, Name = "Wallis and Futuna" },
            new FlagModel() { Code = "ws", FlagSquare = SVGFlags.ws_1, FlagWide = SVGFlags.ws_2, Iso = true, Name = "Samoa" },
            new FlagModel() { Code = "xk", FlagSquare = SVGFlags.xk_1, FlagWide = SVGFlags.xk_2, Iso = false, Name = "Kosovo" },
            new FlagModel() { Code = "xx", FlagSquare = SVGFlags.xx_1, FlagWide = SVGFlags.xx_2, Iso = false, Name = "Unknown" },
            new FlagModel() { Code = "ye", FlagSquare = SVGFlags.ye_1, FlagWide = SVGFlags.ye_2, Iso = true, Name = "Yemen" },
            new FlagModel() { Code = "yt", FlagSquare = SVGFlags.yt_1, FlagWide = SVGFlags.yt_2, Iso = true, Name = "Mayotte" },
            new FlagModel() { Code = "za", FlagSquare = SVGFlags.za_1, FlagWide = SVGFlags.za_2, Iso = true, Name = "South Africa" },
            new FlagModel() { Code = "zm", FlagSquare = SVGFlags.zm_1, FlagWide = SVGFlags.zm_2, Iso = true, Name = "Zambia" },
            new FlagModel() { Code = "zw", FlagSquare = SVGFlags.zw_1, FlagWide = SVGFlags.zw_2, Iso = true, Name = "Zimbabwe" }
        };

        /// <summary>
        /// Gets the name by country code.
        /// </summary>
        /// <param name="code">The code.</param>
        /// <returns></returns>
        public static string GetNameByCountryCode(this string code)
        {
            string rtn = "";

            var fl = FlagModels.Where(f => f.Code.ToLower() == code.ToLower()).FirstOrDefault();
            if (fl != null)
                rtn = fl.Name;

            return rtn;
        }

        /// <summary>
        /// Gets the flag by country code.
        /// </summary>
        /// <param name="code">The code.</param>
        /// <param name="flagType">Type of the flag.</param>
        /// <returns></returns>
        public static string GetFlagByCountryCode(this string code, FlagType flagType)
        {
            string rtn = "";

            var fl = FlagModels.Where(f => f.Code.ToLower() == code.ToLower()).FirstOrDefault();
            if (fl != null)
                rtn = flagType == FlagType.Square ? fl.FlagSquare : fl.FlagWide;
            else
                rtn = flagType == FlagType.Square ? SVGFlags.xx_1 : SVGFlags.xx_2;

            return rtn;
        }
    }
}